/// <reference types="vite/client" />
declare let LazyLoad: LazyLoad;
declare let GLightbox: GLightbox;
declare let gsap: gsap;
declare let Swiper: Swiper;
declare let echarts: echarts;
declare let IMask: IMask;
declare let Handlebars: Handlebars;
declare let Choices: Choices;
declare let rangeSlider: rangeSlider;
declare let Toastify: Toastify;
declare let FloatingUIDOM: FloatingUIDOM;
